version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chroma-data-ingestion
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE=chroma_data
      - MONGO_COLLECTION=analysis_data

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongo_data:
